// Astro 6 content collection for auto-published blog posts.
// Hand-written posts live at src/pages/blog/*.astro and continue to work;
// content-collection posts live under src/content/blog/*.md and render via
// src/pages/blog/[slug].astro.

import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

const blog = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/blog' }),
  schema: z.object({
    title: z.string(),
    slug: z.string(),
    excerpt: z.string(),
    category: z.string(),
    date: z.string(),
    readTime: z.string(),
    image: z.string().optional(),
    tldr: z.string(),
    metaDescription: z.string().max(180),
    tags: z.array(z.string()).default([]),
    autoGenerated: z.boolean().default(true),
    citations: z.array(z.string()).default([]),
    lastUpdated: z.string().optional(),
  }),
});

export const collections = { blog };
